### ISSUE TITLE
actualmente no funciona

### ISSUE THREAD

**Issue by ghost** [dangar16/dontorrent-plugin#1]
Lo he instalado pero nada.

**Comment by dangar16** [comment]
Prueba ahora, he cambiado la url

**Comment by ghost** [comment]
me sigue saliendo la versión 0.4
https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins

**Comment by dangar16** [comment]
Al instalar el plugin de búsqueda, utiliza la opción enlace web y pones el siguiente link [https://raw.githubusercontent.com/dangar16/dontorrent-plugin/main/dontorrent.py](https://raw.githubusercontent.com/dangar16/dontorrent-plugin/main/dontorrent.py). Antes de hacerlo, tienes que borrar el que estaba instalado pulsando en el nombre click izquierdo y desinstalar.

![image](https://github.com/user-attachments/assets/7efd0d2e-0996-4aec-bc35-692d3def59ef)

**Comment by ghost** [comment]
no lo reconoce en cambio el antiguo si, quizás tengas que actualizarlo alli

**Comment by dangar16** [comment]
Al hacerlo te indica algún error? Por si lo podrías compartir

**Comment by ghost** [comment]
no me da error, me dice éxito pero luego no sale en la lista, he probado de agregar torrent Galaxy, rargb, YTS, btdig y elite torrent, todos se ven, compara tu código con alguno de estos y te voy testeando

**Comment by dangar16** [comment]
![image](https://github.com/user-attachments/assets/99ea6c39-9a51-4171-9ec8-e1cd6ef285ab)
Al lado del buscador selecciona dontorrent si te sale y prueba. También intenta acceder a [https://dontorrent.exposed](https://dontorrent.exposed) que es la url vaya a ser que tu ISP te bloquee la url.

**Comment by ghost** [comment]
sigue sin salir en la lista, no tengo ningún bloqueo, la versión de qbittorrent es la 4.6.3

**Comment by ghost** [comment]
he visto que tu forma de escribir el código es diferente a los demás complementos y salen éstas lineas sueltas
class dontorrent(object):
    """
    `url`, `name`, `supported_categories` should be static variables of the engine_name class,
     otherwise qbt won't install the plugin.

**Comment by dangar16** [comment]
Que yo sepa, están bien definidas, plugins como el de 1337x lo tiene igual y funciona. Al igual falla por la versión de qbittorrent, con la 4.6.5 funciona bien. Pero me extraña que siguiendo los pasos ni siquiera te aparezca el plugin en la lista

**Comment by carolinaantes** [comment]
1337x me funciona perfecto voy a mirar el codigo

**Comment by carolinaantes** [comment]
clase one337x(objeto):
    url = 'https://1337x.to'
    nombre = '1337x'
    categorías compatibles = {
        'todos': Ninguno,
        'anime': 'anime',
        'software': 'Aplicaciones',
        'juegos': 'Juegos',
        'películas': 'Películas',
        'música': 'Música',
        'televisión': 'televisión',
    }

**Comment by carolinaantes** [comment]
class dontorrent(object):
    """
    `url`, `name`, `supported_categories` should be static variables of the engine_name class,
     otherwise qbt won't install the plugin.

    `url`: The URL of the search engine.
    `name`: The name of the search engine, spaces and special characters are allowed here.
    `supported_categories`: What categories are supported by the search engine and their corresponding id,
    possible categories are ('all', 'anime', 'books', 'games', 'movies', 'music', 'pictures', 'software', 'tv').
    """

    url = 'https://dontorrent.exposed'
    name = 'dontorrent'
    supported_categories = {

**Comment by carolinaantes** [comment]
class dontorrent(object):
    """
    `url`, `name`, `supported_categories` should be static variables of the engine_name class,
     otherwise qbt won't install the plugin.

    `url`: The URL of the search engine.
    `name`: The name of the search engine, spaces and special characters are allowed here.
    `supported_categories`: What categories are supported by the search engine and their corresponding id,
    possible categories are ('all', 'anime', 'books', 'games', 'movies', 'music', 'pictures', 'software', 'tv').
    """

**Comment by carolinaantes** [comment]
el tuyo empiezo con unas lineas de URL y name vacías, creo que por ahí viene el fallo

**Comment by carolinaantes** [comment]
sale duplicado don torrent object

**Comment by ghost** [comment]
si es muy raro, la verdad es que no puedo probar la 4.6.5 porque estoy en seedbox y no la tienen, tu puedes probar la 4.6.3 por favor

**Comment by iordic** [comment]
Ya he descubierto el problema. Se debe al uso de una expresión (:=) que solo conocen las versiones 3.8+ de Python. Aquí están los detalles: https://docs.python.org/3/whatsnew/3.8.html#assignment-expressions

Aquí se puede ver el fallo al intentar cargar el engine desde _nova2_ para la versión de python que dice @carolinaantes:

![1](https://github.com/user-attachments/assets/f1048054-8868-4984-b349-e937469fed60)

El parche para solucionar su caso particular es cambiar esta línea:

```diff
140c140
<             item['name'] = (name:=i.split("/")[-1].replace("-", " "))
---
>             item['name'] = i.split("/")[-1].replace("-", " ")

```

Tras aplicar este parche ya funciona para la versión 3.7:

![3](https://github.com/user-attachments/assets/2b71da7b-c488-4c9e-885c-ef05b6754b92)

## Replicar fallo:
Para replicar el escenario de @carolinaantes:

1. Descargar el código fuente de la versión [4.6.3 de qbittorrent](https://github.com/qbittorrent/qBittorrent/releases/tag/release-4.6.3).
2. Copiar los ficheros de nova2 para realizar las pruebas, en la carpeta _src/searchengine/nova3_
3. Copiar el engine dentro de la carpeta _engines_
4. Crear un entorno virtual con la versión 3.7.3 y probar a ejecutar `python3 nova2.py`. Si aparece dontorrent en la lista de engines disponibles es que funciona.

Para que muestre el motivo del fallo al cargar el engine aplicar este parche a nova2 (en el Exception de la **línea 79**):
```diff
79a80
>             print(traceback.format_exc())
```

### P.D.
Las malas noticias para @carolinaantes es que si actualizas la versión de qbittorrent, el propio cargador _nova2_ incluye este tipo de expresiones y te fallará. Aquí se puede ver cómo falla para esa versión de python:

![nova2_python_versions](https://github.com/user-attachments/assets/7907032a-b3b0-4208-a6ad-e563c2f47f15)

(He remarcado en verde la ejecución con una versión de python actual y en rojo para la 3.7. En este caso el nova2 es el de la última versión de qbittorrent)

**Comment by dangar16** [comment]
Muchas gracias @iordic porque la verdad ni se me había ocurrido que podía ser eso. Ya está publicado el cambio. Ya dices @carolinaantes si te sigue dando problemas o no.

**Comment by carolinaantes** [comment]
Muchas gracias tanto al creador por este gran plugin y su esfuerzo por actualizarlo como a iordin por encontrar la solución. El que has subido no me funciona, te paso el de iordin que si me funciona.
[dontorrent.txt](https://github.com/user-attachments/files/17103277/dontorrent.txt)

**Comment by ghost** [comment]
y un pequeño detalle que se me ha olvidado poner la d y la t en mayúscula asi saldra ordenado en la lista de buscadores DonTorrent.

**Comment by carolinaantes** [comment]
masnproblemas jaja, el de Jordi si lo acepta a BitTorrent pero he hecho búsquedas y salen todas en blanco.

**Comment by ghost** [comment]
me daba problemas pero porque estaba intentando copiar el py de tu página, ahora me he ido a https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins
y me sale por fin en qbittorrent pero las búsquedas no funcionan.

**Comment by dangar16** [comment]
Ole me alegro de que te funcione
¿A que te refieres con lo de las letras? Que no lo he llegado a pillar del todo

**Comment by ghost** [comment]
no me funciona ahora si se instala en qbittorrent pero las búsquedas no funcionan jeje, pruébalo y me dices.

**Comment by dangar16** [comment]
Sobre el tema de las búsquedas va a veces algo raro, pero es por la página de dontorrent. A veces al hacer una búsqueda salta este mensaje en la página y entonces no puedo pillar nada.
![image](https://github.com/user-attachments/assets/2c962ff4-e698-4935-885c-f0d3d4e0f31b)
Prueba con otras búsquedas y luego prueba en dontorrent a buscar lo mismo para ver si te salta ese mensaje y me dices

**Comment by iordic** [comment]
A mi también me pasa que no saca resultados, es problema de la web sí. Encima para la misma búsqueda a veces saca y otras no, va fatal.

**Comment by ghost** [comment]
Era si puedes escribir dentro el nombre como DonTorrent, la d y la t mayúsculas, en la versión que tengo los nombres en minúsculas los deja debajo del todo.
![Screenshot_20240923_225852~2](https://github.com/user-attachments/assets/a2a67557-fee6-49c0-a052-6c4488d2cab2)
![Screenshot_20240923_225735_SimpleEditorFree~2](https://github.com/user-attachments/assets/b8189655-b6ee-44ba-8678-b6a1fcbcd8b4)

**Comment by dangar16** [comment]
Okay, ya lo tienes cambiado

**Comment by ghost** [comment]
Gracias! lo conseguí 
![Screenshot_20240923_232325~2](https://github.com/user-attachments/assets/3e876a3c-7ea3-4c68-b908-97fc6419de04)

**Comment by ghost** [comment]
atención he encontrado un clon de don torrent pero sin fallos en el buscador quizás os pueda servir para solucionarlo.
https://naranjatorrent.com
https://divxtotal.wtf

**Comment by dangar16** [comment]
He probado varios clones, incluidos esos, pero van peor. El primero me rechaza la conexión y el segundo no me saca ninguna salida

**Comment by ghost** [comment]
https://esmeraldatorrent.com

Ya no conozco otros.

**Comment by ghost** [comment]
Luego hay otros que no son clones pero utilizan la misma base de datos diría, no estoy seguro
https://calidadtorrent.com
https://pediatorrent.com

**Comment by dangar16** [comment]
Estoy probando con la segunda página y va bien, estoy haciendo el plugin pero tardaré lo suyo

**Comment by iordic** [comment]
Creo el issue que se está saliendo del scope inicial, yo cerraría este y abriría nuevos para los diferentes temas 😅

**Comment by ghost** [comment]
yo os ayudaría pero no tengo ni idea de programación.

**Comment by dangar16** [comment]
Tiene razón, voy a cerrarlo. Tambien de paso si podeis mirar este [plugin](https://github.com/dangar16/pediatorrent-plugin) de lujo. Está hecho un poco a lo vago

**Comment by iordic** [comment]
No, pero no digo por tema de programación @carolinaantes. A nivel de GitHub, cada issue debería abrirse para tratar un tema concreto con un título y una descripción claras. Y la discusión centrarse sólo en el tema de este, que cuando está resuelto se cierra y queda archivado.

Piensa que estos luego los usa la gente para ver si alguien ha tenido el mismo problema antes, poder ir al hilo de la discusión y ver cómo se ha resuelto. Por eso el título debe ser bastante autodescriptivo.

Por ejemplo, para este podría haber sido:
- Título: fallo al cargar el engine en qbittorrent
- En la descripción: explicar cuál es el problema, si puedes dar detalles del error y comentar que versiones estás usando.

Y ya una vez resuelto abrir nuevos issues, separados, para los diferentes temas que se están discutiendo aquí. Yo por ejemplo lo habría dividido:
1. Un ticket para el problema actual: que no carga el módulo
2. Modificar el nombre a capitalizado para que se ordene bien en el listado
3. Las búsquedas fallan y no arrojan resultados
4. Mirrors para dontorrent

Ya, ahora sí, centrándome en programación, los issues son como tareas, de hecho están pensados para sacar tareas de estos. Y como tal, cuanto más atomizadas estén mejor son de abordar/solucionar. 

Espero haberme explicado bien y que no haya quedado de regañina, es por mantener las buenas prácticas 🤗

**Comment by ghost** [comment]
si te has explicado bien! muy amables hais con solucionarlo lo de Don torrent, ahora a por el buscador jeje.
