### ISSUE TITLE
No se descarga automáticamente al hacer doble click

### ISSUE THREAD

**Issue by iordic** [dangar16/dontorrent-plugin#2]
Para el método _download_torrent()_ hay que dejar el print() en vez de hacer return, como se explica aquí: https://github.com/qbittorrent/search-plugins/wiki/How-to-write-a-search-plugin#python-class-file-structure

```diff
22c22
<         return download_file(url)
---
>         print(download_file(url))
```

Cuando cambias eso, funciona correctamente sin tener que copiar el enlace a mano, con solo pulsar sobre el elemento con el ratón:
![Screenshot_20240924_100356](https://github.com/user-attachments/assets/135c4194-cd6f-427a-9ea6-627b870aa7d1)

**Comment by dangar16** [comment]
Ya está cambiado :)
